# Generated by Django 3.2.12 on 2024-06-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='grad_level',
            field=models.CharField(default='UG', max_length=2),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='semester',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
