# Generated by Django 3.2.12 on 2024-06-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_teachertable_teacher_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertable',
            name='teacher_acc',
        ),
    ]
