# Generated by Django 3.2.12 on 2024-06-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_teachertable_teacher_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lab_theory',
            field=models.CharField(default='T', max_length=2),
        ),
    ]
