# Generated by Django 3.2.12 on 2024-06-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtimetable',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examtimetable',
            name='grad_level',
        ),
    ]
