# Generated by Django 3.2.12 on 2024-06-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20240616_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtimetable',
            name='time_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examtimetable',
            name='time_to',
            field=models.TimeField(),
        ),
    ]
