# Generated by Django 3.2.12 on 2024-06-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20240616_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachertable',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.department'),
        ),
    ]
