# Generated by Django 3.2.12 on 2024-06-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_teachertable_dept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertable',
            name='designation',
        ),
    ]
