# Generated by Django 3.2.12 on 2024-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_teachertable_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertable',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='teachertable',
            name='username',
            field=models.CharField(default='teacher', max_length=30),
        ),
    ]
