# Generated by Django 3.2.12 on 2024-06-20 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0014_auto_20240620_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyallotment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examtimetable'),
        ),
        migrations.AlterField(
            model_name='dutyallotment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
